apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o deployment
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o deployment
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/snipe-it-snipeit-backend: "true"
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: ALLOW_IFRAMING
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_IFRAMING
                  name: configmap
            - name: API_TOKEN_EXPIRATION_YEARS
              valueFrom:
                configMapKeyRef:
                  key: API_TOKEN_EXPIRATION_YEARS
                  name: configmap
            - name: APP_CIPHER
              valueFrom:
                configMapKeyRef:
                  key: APP_CIPHER
                  name: configmap
            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: APP_DEBUG
                  name: configmap
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  key: APP_ENV
                  name: configmap
            - name: APP_FORCE_TLS
              valueFrom:
                configMapKeyRef:
                  key: APP_FORCE_TLS
                  name: configmap
            - name: APP_KEY
              valueFrom:
                configMapKeyRef:
                  key: APP_KEY
                  name: configmap
            - name: APP_LOCALE
              valueFrom:
                configMapKeyRef:
                  key: APP_LOCALE
                  name: configmap
            - name: APP_LOCKED
              valueFrom:
                configMapKeyRef:
                  key: APP_LOCKED
                  name: configmap
            - name: APP_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  key: APP_TIMEZONE
                  name: configmap
            - name: APP_TRUSTED_PROXIES
              valueFrom:
                configMapKeyRef:
                  key: APP_TRUSTED_PROXIES
                  name: configmap
            - name: APP_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_URL
                  name: configmap
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: configmap
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: configmap
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: configmap
            - name: BACKUP_ENV
              valueFrom:
                configMapKeyRef:
                  key: BACKUP_ENV
                  name: configmap
            - name: CACHE_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: CACHE_DRIVER
                  name: configmap
            - name: CACHE_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: CACHE_PREFIX
                  name: configmap
            - name: COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: COOKIE_DOMAIN
                  name: configmap
            - name: COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  key: COOKIE_NAME
                  name: configmap
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  key: CORS_ALLOWED_ORIGINS
                  name: configmap
            - name: DB_CHARSET
              valueFrom:
                configMapKeyRef:
                  key: DB_CHARSET
                  name: configmap
            - name: DB_COLLATION
              valueFrom:
                configMapKeyRef:
                  key: DB_COLLATION
                  name: configmap
            - name: DB_CONNECTION
              valueFrom:
                configMapKeyRef:
                  key: DB_CONNECTION
                  name: configmap
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: configmap
            - name: DB_DUMP_PATH
              valueFrom:
                configMapKeyRef:
                  key: DB_DUMP_PATH
                  name: configmap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: configmap
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DB_PASSWORD
                  name: configmap
            - name: DB_PREFIX
              valueFrom:
                configMapKeyRef:
                  key: DB_PREFIX
                  name: configmap
            - name: DB_SSL
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL
                  name: configmap
            - name: DB_SSL_CA_PATH
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL_CA_PATH
                  name: configmap
            - name: DB_SSL_CERT_PATH
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL_CERT_PATH
                  name: configmap
            - name: DB_SSL_CIPHER
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL_CIPHER
                  name: configmap
            - name: DB_SSL_IS_PAAS
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL_IS_PAAS
                  name: configmap
            - name: DB_SSL_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  key: DB_SSL_KEY_PATH
                  name: configmap
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: configmap
            - name: ENABLE_CSP
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_CSP
                  name: configmap
            - name: ENABLE_HSTS
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_HSTS
                  name: configmap
            - name: ENCRYPT
              valueFrom:
                configMapKeyRef:
                  key: ENCRYPT
                  name: configmap
            - name: EXPIRE_ON_CLOSE
              valueFrom:
                configMapKeyRef:
                  key: EXPIRE_ON_CLOSE
                  name: configmap
            - name: GOOGLE_MAPS_API
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_MAPS_API
                  name: configmap
            - name: IMAGE_LIB
              valueFrom:
                configMapKeyRef:
                  key: IMAGE_LIB
                  name: configmap
            - name: LDAP_MEM_LIM
              valueFrom:
                configMapKeyRef:
                  key: LDAP_MEM_LIM
                  name: configmap
            - name: LDAP_TIME_LIM
              valueFrom:
                configMapKeyRef:
                  key: LDAP_TIME_LIM
                  name: configmap
            - name: LOGIN_LOCKOUT_DURATION
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_LOCKOUT_DURATION
                  name: configmap
            - name: LOGIN_MAX_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_MAX_ATTEMPTS
                  name: configmap
            - name: LOG_CHANNEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_CHANNEL
                  name: configmap
            - name: LOG_MAX_DAYS
              valueFrom:
                configMapKeyRef:
                  key: LOG_MAX_DAYS
                  name: configmap
            - name: MAIL_AUTO_EMBED_METHOD
              valueFrom:
                configMapKeyRef:
                  key: MAIL_AUTO_EMBED_METHOD
                  name: configmap
            - name: MAIL_BACKUP_NOTIFICATION_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: MAIL_BACKUP_NOTIFICATION_ADDRESS
                  name: configmap
            - name: MAIL_BACKUP_NOTIFICATION_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: MAIL_BACKUP_NOTIFICATION_DRIVER
                  name: configmap
            - name: MAIL_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: MAIL_DRIVER
                  name: configmap
            - name: MAIL_ENCRYPTION
              valueFrom:
                configMapKeyRef:
                  key: MAIL_ENCRYPTION
                  name: configmap
            - name: MAIL_FROM_ADDR
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_ADDR
                  name: configmap
            - name: MAIL_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_FROM_NAME
                  name: configmap
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MAIL_HOST
                  name: configmap
            - name: MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PASSWORD
                  name: configmap
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MAIL_PORT
                  name: configmap
            - name: MAIL_REPLYTO_ADDR
              valueFrom:
                configMapKeyRef:
                  key: MAIL_REPLYTO_ADDR
                  name: configmap
            - name: MAIL_REPLYTO_NAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_REPLYTO_NAME
                  name: configmap
            - name: MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MAIL_USERNAME
                  name: configmap
            - name: MAX_RESULTS
              valueFrom:
                configMapKeyRef:
                  key: MAX_RESULTS
                  name: configmap
            - name: MEMCACHED_HOST
              valueFrom:
                configMapKeyRef:
                  key: MEMCACHED_HOST
                  name: configmap
            - name: MEMCACHED_PORT
              valueFrom:
                configMapKeyRef:
                  key: MEMCACHED_PORT
                  name: configmap
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: configmap
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: configmap
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: configmap
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: configmap
            - name: PRIVATE_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_ACCESS_KEY_ID
                  name: configmap
            - name: PRIVATE_AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_BUCKET
                  name: configmap
            - name: PRIVATE_AWS_BUCKET_ROOT
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_BUCKET_ROOT
                  name: configmap
            - name: PRIVATE_AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_DEFAULT_REGION
                  name: configmap
            - name: PRIVATE_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_SECRET_ACCESS_KEY
                  name: configmap
            - name: PRIVATE_AWS_URL
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_AWS_URL
                  name: configmap
            - name: PRIVATE_FILESYSTEM_DISK
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_FILESYSTEM_DISK
                  name: configmap
            - name: PUBLIC_AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_ACCESS_KEY_ID
                  name: configmap
            - name: PUBLIC_AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_BUCKET
                  name: configmap
            - name: PUBLIC_AWS_BUCKET_ROOT
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_BUCKET_ROOT
                  name: configmap
            - name: PUBLIC_AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_DEFAULT_REGION
                  name: configmap
            - name: PUBLIC_AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_SECRET_ACCESS_KEY
                  name: configmap
            - name: PUBLIC_AWS_URL
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_AWS_URL
                  name: configmap
            - name: PUBLIC_FILESYSTEM_DISK
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_FILESYSTEM_DISK
                  name: configmap
            - name: QUEUE_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: QUEUE_DRIVER
                  name: configmap
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  key: REDIS_HOST
                  name: configmap
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PASSWORD
                  name: configmap
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  key: REDIS_PORT
                  name: configmap
            - name: REFERRER_POLICY
              valueFrom:
                configMapKeyRef:
                  key: REFERRER_POLICY
                  name: configmap
            - name: RESET_PASSWORD_LINK_EXPIRES
              valueFrom:
                configMapKeyRef:
                  key: RESET_PASSWORD_LINK_EXPIRES
                  name: configmap
            - name: SECURE_COOKIES
              valueFrom:
                configMapKeyRef:
                  key: SECURE_COOKIES
                  name: configmap
            - name: SESSION_DRIVER
              valueFrom:
                configMapKeyRef:
                  key: SESSION_DRIVER
                  name: configmap
            - name: SESSION_LIFETIME
              valueFrom:
                configMapKeyRef:
                  key: SESSION_LIFETIME
                  name: configmap
          image: mariadb:10.6.4-focal
          name: mariadb
          ports:
            - containerPort: 3306
              hostPort: 3306
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: dbclaim0
status: {}
